### ISSUE TITLE
Implement CSS Nesting

### ISSUE THREAD

**Issue by nirfse** [y0ssar1an/CSS3#69]
Please dedicate higher priority for the [CSS nesting](https://tabatkins.github.io/specs/css-nesting/) implementation proposed by @tabatkins. This alone would be a huge progress for those of us, who actively use PostCSS's [CSSNext](https://github.com/MoOx/postcss-cssnext) plugin in production.

**Comment by y0ssar1an** [comment]
I worked on this yesterday and couldn't figure it out. I was about to give up and close this issue as out-of-scope, but I may have just cracked it. I still need to figure out `@nest` and do a bunch more testing to make sure I didn't break the world.

I agree that PostCSS support would be a nice improvement. CSS3 already supports about 90% of CSSNext. Here's what's missing:
- custom properties set & @apply
- custom selectors
- nesting

**Comment by y0ssar1an** [comment]
I just pushed preliminary support for nesting to my `nesting` branch. Anybody interested in this feature, please help me test it.
1. Package Control: Remove Package > CSS3
2. `cd <your-sublime-packages-directory>` (e.g. /Users/yourname/Library/Application Support/Sublime Text 3/Packages)
3. Delete any CSS3 files that might've been left behind
4. `git clone https://github.com/y0ssar1an/CSS3.git`
5. `cd CSS3`
6. `git checkout nesting`
7. Open a PostCSS file with nesting and see if everything looks right. I'm particularly interested to see if the completions are still working. I have no automated tests for completions.

**Comment by ihodev** [comment]
@y0ssar1an Thanks a lot for your work! Syntax highlighting looks good for me. Properties completions also works as expected, however I have problems with selector completions.

![1](https://cloud.githubusercontent.com/assets/9801624/20618354/32e0b8ce-b2f7-11e6-911b-fd0584b97e2b.gif)

**Comment by nirfse** [comment]
@y0ssar1an Thank you so much for your contribution. I didn't have a chance to test this branch for any meaningful amount of time. But syntax highlighting and properties auto-completions in nested elements are working flawlessly for me so far. I can confirm @ihodev's report on the lack of elements auto-completion.

This is a solid step forward in my daily work routine, thank you.

**Comment by y0ssar1an** [comment]
Thanks very much for the help! That GIF was especially helpful. I was able to repro the completions issue quickly and I've just pushed an update to fix it.
```sh
cd CSS3
git pull origin post_css
```
Keep up the good work with the testing. I'll prepare a new release shortly. I may change the name to CSS4 to reflect that all the next gen CSS is supported.

**Comment by y0ssar1an** [comment]
All the [`cssnext`](http://cssnext.io) features are now implemented. The `post_css` branch has been merged into `develop`. Please test the `develop` branch a little more and report any issues. If it looks good, I'll tag it and release it. Thanks again for your help!

**Comment by y0ssar1an** [comment]
I just pushed out the [2.1.0](https://github.com/y0ssar1an/CSS3/releases/tag/v2.1.0) release. It should start rolling out to everyone within an hour. Thanks again for your help on this!

**Comment by craigcosmo** [comment]
Nesting still not work. I got your latest version 2.1.0

<img width="474" alt="screen_shot_2017-01-12_at_2_29_09_am" src="https://cloud.githubusercontent.com/assets/538657/21863223/151216a6-d86f-11e6-9ac0-21e529f13a41.png">

**Comment by nirfse** [comment]
@craigcosmo, based on the [draft standard](https://tabatkins.github.io/specs/css-nesting/) you have to use `&` selector as a pointer to parent element. Thus, in order to style child element `.logo` of parent element `.home`, you have to use following syntax:
```
.home {
    color: red;
    font-size: 10px;
    & .logo { color: blue }
}
```
This draft standard syntax if correctly highlighted by current CSS3 plugin.
